# Generated by Django 3.2.21 on 2023-09-14 19:33

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=django_quill.fields.QuillField(),
        ),
    ]
