# Generated by Django 3.2.21 on 2023-09-12 22:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('playground', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostActivity',
            new_name='Activity',
        ),
    ]
