# Generated by Django 3.2.21 on 2023-09-12 22:28

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0002_rename_postactivity_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='featured_image',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[400, None], upload_to='activities/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
