# Generated by Django 3.2.21 on 2023-09-12 22:52

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('playground', '0003_auto_20230912_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='content',
            field=djrichtextfield.models.RichTextField(max_length=500),
        ),
    ]
